[2022-11-30 14:27:35,645] WARNING in _internal:  * Debugger is active!
[2022-11-30 14:28:40,569] WARNING in _internal:  * Debugger is active!
[2022-11-30 14:32:17,332] WARNING in _internal:  * Debugger is active!
[2022-11-30 14:35:55,297] WARNING in _internal:  * Debugger is active!
[2022-11-30 14:45:23,319] WARNING in _internal:  * Debugger is active!
[2022-11-30 14:49:00,401] WARNING in _internal:  * Debugger is active!
[2022-11-30 15:03:24,590] WARNING in _internal:  * Debugger is active!
[2022-11-30 15:07:34,299] WARNING in _internal:  * Debugger is active!
[2022-11-30 16:08:07,181] WARNING in _internal:  * Debugger is active!
[2022-11-30 15:13:01,365] ERROR in app: Exception on /user/shopping-bag [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/grey/WebProject/team_2web/blueprint/user_blueprint.py", line 211, in shopping_bag
    for order in user.shoppingList[0].orders:
AttributeError: 'NoneType' object has no attribute 'shoppingList'
[2022-11-30 15:54:09,774] ERROR in app: Exception on /search/ [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/grey/WebProject/team_2web/app.py", line 110, in search
    return render_template("search_result.html", page_data=page_data, keywords=keyword, searchForm=search_form)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/grey/WebProject/team_2web/templates/search_result.html", line 41, in template
    {% block jsLink %
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '%'
[2022-11-30 15:54:30,825] ERROR in app: Exception on /search/ [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/grey/WebProject/team_2web/app.py", line 110, in search
    return render_template("search_result.html", page_data=page_data, keywords=keyword, searchForm=search_form)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/grey/WebProject/team_2web/templates/search_result.html", line 41, in template
    {% block jsLink %
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '%'
[2022-11-30 17:28:23,052] WARNING in _internal:  * Debugger is active!
[2022-11-30 17:28:26,071] WARNING in _internal:  * Debugger is active!
[2022-11-30 17:32:52,083] WARNING in _internal:  * Debugger is active!
[2022-11-30 17:34:58,537] WARNING in _internal:  * Debugger is active!
[2022-11-30 17:35:21,947] WARNING in _internal:  * Debugger is active!
[2022-11-30 17:36:28,637] WARNING in _internal:  * Debugger is active!
[2022-11-30 17:38:09,014] WARNING in _internal:  * Debugger is active!
[2022-11-30 17:50:02,111] WARNING in _internal:  * Debugger is active!
[2022-11-30 17:51:45,573] WARNING in _internal:  * Debugger is active!
[2022-12-01 23:20:32,671] WARNING in _internal:  * Debugger is active!
[2022-12-02 00:03:14,760] WARNING in _internal:  * Debugger is active!
[2022-12-02 00:05:56,182] WARNING in _internal:  * Debugger is active!
